#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 06 21:50:46 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Derivative Main d24.4.14.zip
enableShaders=false
